project:
  type: website
  output-dir: slides
  resources:
    - "*.html"
website: 
  title: "CPSC 330 Section 102 Slides"
  page-navigation: true
  navbar:
    title: "CPSC 330 Section 102"
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Slides        
  sidebar:
    - id: slides
      contents:
        - slides-01-intro.qmd
format:
  html:
    theme: [zephyr]
    toc: false
    lightbox: true
          
editor:
  render-on-save: true

execute:
  freeze: auto
  